on:
  push:
    paths-ignore:
      - 'readme.md'
      - '.gitignore'
    branches:
      - main

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Install Prerequisites
      run: .\build\vsts-prerequisites.ps1
      shell: powershell
    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: powershell
    - name: Build
      run: .\build\vsts-build.ps1 -ApiKey $env:APIKEY -IncludeGitHubRelease -AutoVersion
      shell: powershell
      env:
        APIKEY: ${{ secrets.ApiKey }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          *.nupkg